CREATE TABLE IF NOT EXISTS oc_feedback_response (
    id BIGINT NOT NULL AUTO_INCREMENT,
    submitted_at DATETIME NULL,
    term_year VARCHAR(100) NULL,
    login_id BIGINT NULL,
    acad_no VARCHAR(100) NOT NULL,
    `rank` VARCHAR(100) NOT NULL,
    name VARCHAR(255) NULL,
    bn VARCHAR(100) NULL,
    coy VARCHAR(100) NULL,
    cabin_no VARCHAR(100) NOT NULL,
    furniture_issued INT NULL,
    electrical_gadgets INT NULL,
    electricity_hot_water INT NULL,
    leakage_seepage VARCHAR(20) NULL,
    mess_food_quality INT NULL,
    mess_menu_variety INT NULL,
    mess_quantity INT NULL,
    mess_staff_behaviour INT NULL,
    mess_overall INT NULL,
    kapoor_quality INT NULL,
    kapoor_price INT NULL,
    kapoor_stitching INT NULL,
    mec_quality INT NULL,
    mec_price INT NULL,
    mec_overall INT NULL,
    ord_issue_serviceable VARCHAR(20) NULL,
    bicycle_condition INT NULL,
    bicycle_maintenance INT NULL,
    medical_access INT NULL,
    medical_behaviour INT NULL,
    banking_facilities VARCHAR(100) NULL,
    csd_stores INT NULL,
    csd_billing_counters INT NULL,
    suggestion1 VARCHAR(1000) NULL,
    suggestion2 VARCHAR(1000) NULL,
    suggestion3 VARCHAR(1000) NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
